In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [29]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [31]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

c:\Users\keerthi\anaconda3\envs\python_course\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [32]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9962962962962963

In [33]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test, y_test)

0.9796296296296296

In [34]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [35]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [36]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [37]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [ ]:
from sklearn.svm import SVC
score_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

In [23]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [24]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [27]:
scores_rf

[0.9348914858096828, 0.9449081803005008, 0.9198664440734557]

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\keerthi\anaconda3\envs\python_course\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\keerthi\anaconda3\envs\python_course\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linea

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])